### ISSUE TITLE
Getting error while loading a class in initializer

### ISSUE THREAD

**Issue by sudeep-vineti** [hashwin/paper_trail-hashdiff#1]
We added a gem entry in Gemfile as follows
```
gem 'paper_trail-hashdiff', '~> 0.0.4'
```

And after running bundle install, added a config in `paper_trail.rb` in initializers as mentioned as follows
```
PaperTrail.config.object_changes_adapter = PaperTrailHashDiff.new
```

But when we boot rails server we are getting an following error
```
uninitialized constant PaperTrailHashDiff (NameError)
```

Are we missing something here?

**Comment by JeffKandel** [comment]
I am getting the same error.

**Comment by hashwin** [comment]
@sudeep-vineti @JeffKandel just pushed a new  version (0.0.6) that should resolve the issue

**Comment by mazondo** [comment]
This doesn't seem to be resolved yet - I'm still getting it with `0.1.1`

**Comment by hashwin** [comment]
@mazondo Have you tried requiring it in the initializer? i.e.
```
require 'paper_trail_hashdiff'
PaperTrail.config.object_changes_adapter = PaperTrailHashDiff.new
```

**Comment by mazondo** [comment]
that did it! thanks!
